plugins {
    id 'com.android.application'
}

android {
    namespace 'com.dlt.studentcompanion'
    compileSdk 36

    buildFeatures {
        buildConfig = true
    }

    defaultConfig {
        applicationId 'com.dlt.studentcompanion'
        minSdk 26
        targetSdk 36
        versionCode 531407
        versionName '53.3-rc14.7'
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies {
    implementation 'androidx.core:core:1.15.0'
}
